name: Swift Format Check

on:
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Swift Format
      run: |
        brew install swift-format
    
    - name: Check Swift formatting
      run: |
        # Run swift format and capture output
        swift format . --recursive --in-place
        
        # Check if there are any changes
        if ! git diff --exit-code; then
          echo "❌ Swift formatting check failed!"
          echo "The following files need formatting:"
          git diff --name-only
          echo ""
          echo "Please run 'swift format . --recursive --in-place' and commit the changes."
          exit 1
        else
          echo "✅ All Swift files are properly formatted!"
        fi